<div class="actions dropdown example-dropdown-5">
    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">Select item</span>
    <ul class="dropdown">
        <li>
            <span class="item">First item</span>
        </li>
        <li>
            <span class="item">Second item</span>
        </li>
        <li>
            <span class="item">Last item</span>
        </li>
    </ul>
</div>
